config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :sessions      => "users/sessions",
    :registrations => "users/registrations",
    :passwords     => "users/passwords",
  }
  root 'home#index'
  get '/home_serach' => 'home#home_serach'

  resources :abouts, only: [:index]
  resources :searchs, only: [:index]
  resources :car_searchs, only: [:index]
  get '/detail_search' => 'car_searchs#detail_search'
  resources :questions, only: [:index]
  resources :news, only: [:index]
  resources :stores, only: [:index]
  resources :cars, only: [:index]
  post '/reserve' => 'cars#reserve'
  get '/reserved' => 'cars#reserved'

  resources :mypages, only: [:index]
  get '/profile' => 'mypages#profile'
  post '/profile_create' => 'mypages#profile_create'
  patch '/profile_update' => 'mypages#profile_update'
  get '/license' => 'mypages#license'
  post '/license_create' => 'mypages#license_create'
  patch '/license_update' => 'mypages#license_update'
  get '/review' => 'mypages#review'
  post '/review_create' => 'mypages#review_create'
  get '/notification' => 'mypages#notification'
  post '/notification_set' => 'mypages#notification_set'
  get '/payment' => 'mypages#payment'
  get '/privacy' => 'mypages#privacy'
  get '/password' => 'mypages#password'
  post '/password_set' => 'mypages#password_set'
  get '/detail' => 'mypages#detail'
  post '/detail_set' => 'mypages#detail_set'
  get '/reservation' => 'mypages#reservation'

  resources :ownerpages, only: [:index]
  get '/entry' => 'ownerpages#entry'
  post '/owner_create' => 'ownerpages#owner_create'
  get '/performance' => 'ownerpages#performance'
  get '/revenue' => 'ownerpages#revenue'
  get '/consider' => 'ownerpages#consider'
  get '/not_approval' => 'ownerpages#not_approval'
  get '/not_acceptance' => 'ownerpages#not_acceptance'
  get '/car_edit' => 'ownerpages#car_edit'
  patch '/car_update' => 'ownerpages#car_update'
  get '/owner_profile' => 'ownerpages#owner_profile'
  patch '/owner_profile_update' => 'ownerpages#owner_profile_update'
  get '/owner_license' => 'ownerpages#owner_license'
  patch '/owner_license_update' => 'ownerpages#owner_license_update'
  get '/owner_notification' => 'ownerpages#owner_notification'
  get '/owner_account' => 'ownerpages#owner_account'
  post '/owner_account_create' => 'ownerpages#owner_account_create'
  patch '/owner_account_update' => 'ownerpages#owner_account_update'
  get '/owner_privacy' => 'ownerpages#owner_privacy'
  get '/owner_password' => 'ownerpages#owner_password'
  get '/owner_detail' => 'ownerpages#owner_detail'
  post '/store_select' => 'ownerpages#store_select'


  resources :reserve_conditions, only: [:index]
  get '/reserve01' => 'reserves#reserve01'
  get '/reserve02' => 'reserves#reserve02'
  get '/reserve03' => 'reserves#reserve03'
  post '/pay' => 'reserves#pay'

  resources :admins, only: [:index]
  get '/admin_store' => 'admins#admin_store'
  post '/admin_store_create' => 'admins#admin_store_create'
  get '/admin_license' => 'admins#admin_license'
  get '/admin_user' => 'admins#admin_user'
  patch '/role_change' => 'admins#role_change'
  patch '/store_change' => 'admins#store_change'
  get '/admin_store_edit' => 'admins#admin_store_edit'
  patch '/admin_store_update' => 'admins#admin_store_update'
  get '/admin_license_approval' => 'admins#admin_license_approval'
  get '/admin_reservation' => 'admins#admin_reservation'
  get '/admin_return_car' => 'admins#admin_return_car'

  resources :store_admins, only: [:index]
  get '/owner_entry' => 'store_admins#owner_entry'
  get '/owner_acceptance' => 'store_admins#owner_acceptance'
  get '/store_admin_edit' => 'store_admins#store_admin_edit'
  patch '/store_admin_update' => 'store_admins#store_admin_update'
  get '/owner_entry_infomation' => 'store_admins#owner_entry_infomation'
  post '/owner_approval' => 'store_admins#owner_approval'
  get '/owner_acceptance_car' => 'store_admins#owner_acceptance_car'
  get '/acceptance_car' => 'store_admins#acceptance_car'
  post '/owner_car_create' => 'store_admins#owner_car_create'
  get '/acceptance_car_edit' => 'store_admins#acceptance_car_edit'
  patch '/acceptance_car_update' => 'store_admins#acceptance_car_update'
  get '/store_admin_reservation' => 'store_admins#store_admin_reservation'
  get '/receipt_date_set' => 'store_admins#receipt_date_set'
  get '/store_return_car' => 'store_admins#store_return_car'
end

app/views/admins/admin_license.html.slim
= stylesheet_link_tag "home/admin", :media => "all"

article
  section.admin
    h1 管理画面
    .contents
      .nav_toggle_button メニュー
      .ownerpage_nav
        ul
          li
            = link_to "店舗一覧", admins_path
          li
            = link_to "店舗登録", admin_store_path
          li
            = link_to "免許証の確認待ち", admin_license_path, class: "selected"
          li
            = link_to "ユーザ一覧", admin_user_path
          li
            = link_to "予約一覧", admin_reservation_path
      .admin_contents
        h2 免許証の確認待ち
        .admin_contents_inner
          .license_lists
            table
              thead
                tr
                  th ユーザー名
                  th 画像
                  th 状態
              tbody
                -@licenses.each do |license|
                  tr
                    td
                      -if license.user.profile
                        =license.user.profile.try(:name)
                    td =image_tag(license.image.to_s)
                    td
                      -if license.approval
                        p 承認済み
                      -else
                        =link_to "承認する", admin_license_approval_path(id: license.id)
                = paginate @licenses

app/views/admins/admin_reservation.html.slim
= stylesheet_link_tag "home/admin", :media => "all"

article
  section.admin
    h1 管理画面
    .contents
      .nav_toggle_button メニュー
      .ownerpage_nav
        ul
          li
            = link_to "店舗一覧", admins_path
          li
            = link_to "店舗登録", admin_store_path
          li
            = link_to "免許証の確認待ち", admin_license_path
          li
            = link_to "ユーザ一覧", admin_user_path
          li
            = link_to "予約一覧", admin_reservation_path, class: "selected"
      .admin_contents
        h2 予約一覧
        .admin_contents_inner
          .admin_reservelists
            table
              thead
                tr
                  th 車名
                  th 予約日
                  th 返却日
                  th 料金
                  th 状態
              tbody
                -@reservations.each do |reservation|
                  tr
                    td = reservation.car.name
                    td #{reservation.start_date.strftime('%Y年%m月%d日')}#{reservation.start_time.strftime('%H:%M')}
                    td #{reservation.end_date.strftime('%Y年%m月%d日')}#{reservation.end_time.strftime('%H:%M')}
                    td = reservation.total
                    td
                      -if reservation.state == "returned"
                        p 返却ずみ
                      -elsif reservation.state == "rental"
                        =link_to "返却完了", admin_return_car_path(res_id: reservation.id, tab: "returned")
                      -elsif reservation.state == "acceptance"
                        =link_to "受け渡し完了", admin_return_car_path(res_id: reservation.id, tab: "rental")
                = paginate @reservations

app/views/admins/admin_store.html.slim
= stylesheet_link_tag "home/admin", :media => "all"

article
  section.admin
    h1 管理画面
    .contents
      .nav_toggle_button メニュー
      .ownerpage_nav
        ul
          li
            = link_to "店舗一覧", admins_path
          li
            = link_to "店舗登録", admin_store_path, class: "selected"
          li
            = link_to "免許証の確認待ち", admin_license_path
          li
            = link_to "ユーザ一覧", admin_user_path
          li
            = link_to "予約一覧", admin_reservation_path
      .admin_contents
        h2 店舗登録
        .admin_contents_inner
          =simple_form_for Store.new, url: admin_store_create_path  do |f|
            p　店舗名
            = f.input :name, label: false
            p 電話番号
            = f.input :tel, label: false
            p メールアドレス
            = f.input :email, label: false
            p 画像
            = f.input :image, label: false, as: :file
            p 店舗URL
            = f.input :url, label: false
            p アクセス
            = f.input :access, label: false
            p 営業開始時間
            = f.input :business_hour_start, label: false
            p 営業終了時間
            = f.input :business_hour_end, label: false
            p 郵便番号
            = f.input :zip_code, label: false
            p 住所
            = f.input :address, label: false
            p 緯度(Map表示用)
            =link_to "こちらに住所を入力で検索可能", "https://www.geocoding.jp", target: "_blank"
            = f.input :latitude, label: false
            p 経度(Map表示用)
            =link_to "こちらに住所を入力で検索可能", "https://www.geocoding.jp", target: "_blank"
            = f.input :longitude, label: false
            p 都道府県(検索用)
            = f.input :prefecture_id, label: false, collection: Prefecture.all, label_method: :name, value_method: :id
            = f.button :submit, "登録"

app/views/admins/admin_store_edit.html.slim
= stylesheet_link_tag "home/admin", :media => "all"

article
  section.admin
    h1 管理画面
    .contents
      .nav_toggle_button メニュー
      .ownerpage_nav
        ul
          li
            = link_to "店舗一覧", admins_path, class: "selected"
          li
            = link_to "店舗登録", admin_store_path
          li
            = link_to "免許証の確認待ち", admin_license_path
          li
            = link_to "ユーザ一覧", admin_user_path
          li
            = link_to "予約一覧", admin_reservation_path
      .admin_contents
        h2 店舗編集
        .admin_contents_inner
          =simple_form_for @store, url: admin_store_update_path(id: @store.id)  do |f|
            p　店舗名
            = f.input :name, label: false
            p 電話番号
            = f.input :tel, label: false
            p メールアドレス
            = f.input :email, label: false
            p 画像
            = f.input :image, label: false, as: :file
            p 店舗URL
            = f.input :url, label: false
            p アクセス
            = f.input :access, label: false
            p 営業開始時間
            = f.input :business_hour_start, label: false
            p 営業終了時間
            = f.input :business_hour_end, label: false
            p 郵便番号
            = f.input :zip_code, label: false
            p 住所
            = f.input :address, label: false
            p 緯度(Map表示用)
            =link_to "こちらに住所を入力で検索可能", "https://www.geocoding.jp", target: "_blank"
            = f.input :latitude, label: false
            p 経度(Map表示用)
            =link_to "こちらに住所を入力で検索可能", "https://www.geocoding.jp", target: "_blank"
            = f.input :longitude, label: false
            p 都道府県(検索用)
            = f.input :prefecture_id, label: false, collection: Prefecture.all, label_method: :name, value_method: :id
            = f.button :submit, "更新"

app/views/admins/admin_user.html.slim
= stylesheet_link_tag "home/admin", :media => "all"

article
  section.admin
    h1 管理画面
    .contents
      .nav_toggle_button メニュー
      .ownerpage_nav
        ul
          li
            = link_to "店舗一覧", admins_path
          li
            = link_to "店舗登録", admin_store_path
          li
            = link_to "免許証の確認待ち", admin_license_path
          li
            = link_to "ユーザ一覧", admin_user_path, class: "selected"
          li
            = link_to "予約一覧", admin_reservation_path
      .admin_contents
        h2 ユーザー一覧
        .admin_contents_inner
          .admin_user
            table
              thead
                tr
                  th メールアドレス
                  th 店舗
                  th 権限
              tbody
                - @users.each do |user|
                  tr
                    td= user.email
                    td= select_tag :store_id, options_for_select(Store.all.map{|store|store.name},user.store.try(:name)),{:onchange => 'change_store(this)',:include_blank => true, id:user.id}
                    td= select_tag :role, options_for_select([["管理者", "admin"],["契約店", "contracted"]], user.roles.map{|role| role.name}.join(", ")), {:onchange => 'change_role(this)', :include_blank => true, id:user.id}
            = paginate @users

javascript:
  function change_role(data){
    var selecter = data.selectedIndex;
    var value = data.options[selecter].value;
    $.ajax({
      type: 'patch',
      url: 'role_change',
      data: {id: data.id , role: value}
    });
  };

  function change_store(data){
    var selecter = data.selectedIndex;
    var value = data.options[selecter].value;
    $.ajax({
      type: 'patch',
      url: 'store_change',
      data: {id: data.id , store: value}
    });
  };

app/views/admins/index.html.slim
= stylesheet_link_tag "home/admin", :media => "all"

article
  section.admin
    h1 管理画面
    .contents
      .nav_toggle_button メニュー
      .ownerpage_nav
        ul
          li
            = link_to "店舗一覧", admins_path, class: "selected"
          li
            = link_to "店舗登録", admin_store_path
          li
            = link_to "免許証の確認待ち", admin_license_path
          li
            = link_to "ユーザ一覧", admin_user_path
          li
            = link_to "予約一覧", admin_reservation_path
      .admin_contents
        h2 店舗一覧
        .admin_contents_inner
          .store_lists
            table
              thead
                tr
                  th 店舗名
                  th 住所
                  th 電話番号
                  th 
              tbody
                -@stores.each do |store|
                  tr
                    td = store.name
                    td = store.address
                    td = store.tel
                    td = link_to '編集', admin_store_edit_path(id: store.id)
                = paginate @stores