config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :sessions      => "users/sessions",
    :registrations => "users/registrations",
    :passwords     => "users/passwords",
  }
  root 'home#index'
  get '/home_serach' => 'home#home_serach'

  resources :abouts, only: [:index]
  resources :searchs, only: [:index]
  resources :car_searchs, only: [:index]
  get '/detail_search' => 'car_searchs#detail_search'
  resources :questions, only: [:index]
  resources :news, only: [:index]
  resources :stores, only: [:index]
  resources :cars, only: [:index]
  post '/reserve' => 'cars#reserve'
  get '/reserved' => 'cars#reserved'

  resources :mypages, only: [:index]
  get '/profile' => 'mypages#profile'
  post '/profile_create' => 'mypages#profile_create'
  patch '/profile_update' => 'mypages#profile_update'
  get '/license' => 'mypages#license'
  post '/license_create' => 'mypages#license_create'
  patch '/license_update' => 'mypages#license_update'
  get '/review' => 'mypages#review'
  post '/review_create' => 'mypages#review_create'
  get '/notification' => 'mypages#notification'
  post '/notification_set' => 'mypages#notification_set'
  get '/payment' => 'mypages#payment'
  get '/privacy' => 'mypages#privacy'
  get '/password' => 'mypages#password'
  post '/password_set' => 'mypages#password_set'
  get '/detail' => 'mypages#detail'
  post '/detail_set' => 'mypages#detail_set'
  get '/reservation' => 'mypages#reservation'

  resources :ownerpages, only: [:index]
  get '/entry' => 'ownerpages#entry'
  post '/owner_create' => 'ownerpages#owner_create'
  get '/performance' => 'ownerpages#performance'
  get '/revenue' => 'ownerpages#revenue'
  get '/consider' => 'ownerpages#consider'
  get '/not_approval' => 'ownerpages#not_approval'
  get '/not_acceptance' => 'ownerpages#not_acceptance'
  get '/car_edit' => 'ownerpages#car_edit'
  patch '/car_update' => 'ownerpages#car_update'
  get '/owner_profile' => 'ownerpages#owner_profile'
  patch '/owner_profile_update' => 'ownerpages#owner_profile_update'
  get '/owner_license' => 'ownerpages#owner_license'
  patch '/owner_license_update' => 'ownerpages#owner_license_update'
  get '/owner_notification' => 'ownerpages#owner_notification'
  get '/owner_account' => 'ownerpages#owner_account'
  post '/owner_account_create' => 'ownerpages#owner_account_create'
  patch '/owner_account_update' => 'ownerpages#owner_account_update'
  get '/owner_privacy' => 'ownerpages#owner_privacy'
  get '/owner_password' => 'ownerpages#owner_password'
  get '/owner_detail' => 'ownerpages#owner_detail'
  post '/store_select' => 'ownerpages#store_select'


  resources :reserve_conditions, only: [:index]
  get '/reserve01' => 'reserves#reserve01'
  get '/reserve02' => 'reserves#reserve02'
  get '/reserve03' => 'reserves#reserve03'
  post '/pay' => 'reserves#pay'

  resources :admins, only: [:index]
  get '/admin_store' => 'admins#admin_store'
  post '/admin_store_create' => 'admins#admin_store_create'
  get '/admin_license' => 'admins#admin_license'
  get '/admin_user' => 'admins#admin_user'
  patch '/role_change' => 'admins#role_change'
  patch '/store_change' => 'admins#store_change'
  get '/admin_store_edit' => 'admins#admin_store_edit'
  patch '/admin_store_update' => 'admins#admin_store_update'
  get '/admin_license_approval' => 'admins#admin_license_approval'
  get '/admin_reservation' => 'admins#admin_reservation'
  get '/admin_return_car' => 'admins#admin_return_car'

  resources :store_admins, only: [:index]
  get '/owner_entry' => 'store_admins#owner_entry'
  get '/owner_acceptance' => 'store_admins#owner_acceptance'
  get '/store_admin_edit' => 'store_admins#store_admin_edit'
  patch '/store_admin_update' => 'store_admins#store_admin_update'
  get '/owner_entry_infomation' => 'store_admins#owner_entry_infomation'
  post '/owner_approval' => 'store_admins#owner_approval'
  get '/owner_acceptance_car' => 'store_admins#owner_acceptance_car'
  get '/acceptance_car' => 'store_admins#acceptance_car'
  post '/owner_car_create' => 'store_admins#owner_car_create'
  get '/acceptance_car_edit' => 'store_admins#acceptance_car_edit'
  patch '/acceptance_car_update' => 'store_admins#acceptance_car_update'
  get '/store_admin_reservation' => 'store_admins#store_admin_reservation'
  get '/receipt_date_set' => 'store_admins#receipt_date_set'
  get '/store_return_car' => 'store_admins#store_return_car'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @reviews = Review.order(created_at: :desc).limit(5)
    @informations = Information.order(created_at: :desc).limit(5)
  end

  def home_serach
    @tag = params[:tag]
  end
end

app/views/home/_area_serach.html.slim
ul.serch_category
  li
    = link_to "場所から探す", home_serach_path(tag: "area"), { remote: true, class: "selected" }
  li
    = link_to "車体から探す", home_serach_path(tag: "car"), { remote: true }
  li
    = link_to "特集から探す", home_serach_path(tag: "feature"), { remote: true }
table
  tr
    th 北海道地方
    td
      ul
        li
          = link_to "北海道", car_searchs_path(pre: "PRE1")
  tr
    th 東北地方
    td
      ul
        li
          = link_to "青森県", car_searchs_path(pre: "PRE2")
        li
          = link_to "岩手県", car_searchs_path(pre: "PRE3")
        li
          = link_to "宮城県", car_searchs_path(pre: "PRE4")
        li
          = link_to "秋田県", car_searchs_path(pre: "PRE5")
        li
          = link_to "山形県", car_searchs_path(pre: "PRE6")
        li
          = link_to "福島県", car_searchs_path(pre: "PRE7")
  tr
    th 関東地方
    td
      ul
        li
          = link_to "茨木県", car_searchs_path(pre: "PRE8")
        li
          = link_to "栃木県", car_searchs_path(pre: "PRE9")
        li
          = link_to "群馬県", car_searchs_path(pre: "PRE10")
        li
          = link_to "埼玉県", car_searchs_path(pre: "PRE11")
        li
          = link_to "千葉県", car_searchs_path(pre: "PRE12")
        li
          = link_to "東京都", car_searchs_path(pre: "PRE13")
        li
          = link_to "埼玉県", car_searchs_path(pre: "PRE14")
  tr
    th 中部地方
    td
      ul
        li
          = link_to "新潟県", car_searchs_path(pre: "PRE15")
        li
          = link_to "富山県", car_searchs_path(pre: "PRE16")
        li
          = link_to "石川県", car_searchs_path(pre: "PRE17")
        li
          = link_to "福井県", car_searchs_path(pre: "PRE18")
        li
          = link_to "山梨県", car_searchs_path(pre: "PRE19")
        li
          = link_to "長野県", car_searchs_path(pre: "PRE20")
        li
          = link_to "岐阜県", car_searchs_path(pre: "PRE21")
        li
          = link_to "静岡県", car_searchs_path(pre: "PRE22")
        li
          = link_to "愛知県", car_searchs_path(pre: "PRE23")
  tr
    th 近畿地方
    td
      ul
        li
          = link_to "三重県", car_searchs_path(pre: "PRE24")
        li
          = link_to "滋賀県", car_searchs_path(pre: "PRE25")
        li
          = link_to "京都府", car_searchs_path(pre: "PRE26")
        li
          = link_to "大阪府", car_searchs_path(pre: "PRE27")
        li
          = link_to "兵庫県", car_searchs_path(pre: "PRE28")
        li
          = link_to "奈良県", car_searchs_path(pre: "PRE29")
        li
          = link_to "和歌山県", car_searchs_path(pre: "PRE30")
  tr
    th 中国地方
    td
      ul
        li
          = link_to "鳥取県", car_searchs_path(pre: "PRE31")
        li
          = link_to "島根県", car_searchs_path(pre: "PRE32")
        li
          = link_to "岡山県", car_searchs_path(pre: "PRE33")
        li
          = link_to "広島県", car_searchs_path(pre: "PRE34")
        li
          = link_to "山口県", car_searchs_path(pre: "PRE35")
  tr
    th 四国地方
    td
      ul
        li
          = link_to "徳島県", car_searchs_path(pre: "PRE36")
        li
          = link_to "愛媛県", car_searchs_path(pre: "PRE37")
        li
          = link_to "香川県", car_searchs_path(pre: "PRE38")
        li
          = link_to "高知県", car_searchs_path(pre: "PRE39")
  tr
    th 九州地方
    td
      ul
        li
          = link_to "福岡県", car_searchs_path(pre: "PRE40")
        li
          = link_to "佐賀県", car_searchs_path(pre: "PRE41")
        li
          = link_to "長崎県", car_searchs_path(pre: "PRE42")
        li
          = link_to "熊本県", car_searchs_path(pre: "PRE43")
        li
          = link_to "大分県", car_searchs_path(pre: "PRE44")
        li
          = link_to "鹿児島県", car_searchs_path(pre: "PRE45")
        li
          = link_to "宮崎県", car_searchs_path(pre: "PRE46")
        li
          = link_to "沖縄県", car_searchs_path(pre: "PRE47")

app/views/home/_car_serach.html.slim
ul.serch_category
  li
    = link_to "場所から探す", home_serach_path(tag: "area"), { remote: true }
  li
    = link_to "車体から探す", home_serach_path(tag: "car"), { remote: true, class: "selected" }
  li
    = link_to "特集から探す", home_serach_path(tag: "feature"), { remote: true }

table
  tr
    th 基本車輛クラス
    td
      ul
        li
          = link_to "Ｍ", car_searchs_path(cat: "CAT1")
        li
          = link_to "Ｍ(軽)", car_searchs_path(cat: "CAT2")
        li
          = link_to "B", car_searchs_path(cat: "CAT3")
        li
          = link_to "L", car_searchs_path(cat: "CAT4")
        li
          = link_to "1BOX", car_searchs_path(cat: "CAT5")
        li
          = link_to "HV", car_searchs_path(cat: "CAT6")
  tr
    th SPクラス
    td
      ul
        li
          = link_to "Ｍ-SP", car_searchs_path(cat: "CAT7")
        li
          = link_to "Ｍ(軽)-SP", car_searchs_path(cat: "CAT8")
        li
          = link_to "B-SP", car_searchs_path(cat: "CAT9")
        li
          = link_to "L-SP", car_searchs_path(cat: "CAT10")
        li
          = link_to "1BOX-SP", car_searchs_path(cat: "CAT11")
        li
          = link_to "HV-SP", car_searchs_path(cat: "CAT12")
  tr
    th 貨物車輛クラス
    td
      ul
        li
          = link_to "T1", car_searchs_path(cat: "CAT13")
        li
          = link_to "T1(軽)", car_searchs_path(cat: "CAT14")
        li
          = link_to "T1-SP", car_searchs_path(cat: "CAT15")
        li
          = link_to "T2", car_searchs_path(cat: "CAT16")
        li
          = link_to "T3", car_searchs_path(cat: "CAT17")

app/views/home/_feature_serach.html.slim
ul.serch_category
  li
    = link_to "場所から探す", home_serach_path(tag: "area"), { remote: true }
  li
    = link_to "車体から探す", home_serach_path(tag: "car"), { remote: true }
  li
    = link_to "特集から探す", home_serach_path(tag: "feature"), { remote: true, class: "selected" }

app/views/home/_news.html.slim
ul
  -@informations.each do |information|
    li
      | #{information.display_date.strftime('%Y年%m月%d日')}
      span =information.title

app/views/home/_review.html.slim
ul.js-flickity
  -@reviews.each do |review|
    -if review.user.try(:profile)
      li.review_cell
        -if review.user.profile.image?
          =image_tag(review.user.profile.image.to_s, :class => "review_img")
        -else
          =image_tag("review.png", :class => "review_img")
        p.review_profile
          | #{review.user.profile.name}
          span.text01 さん（#{review.user.profile.age}歳）
          br
          span.text02 #{review.user.profile.profession}
        section.review_text
          h3 =review.title
          p =review.description

app/views/home/home_serach.js.erb
<% if @tag == "area" %>
  $('.partial_box').html("<%= j (render 'area_serach') %>");
<% elsif @tag == "car" %>
  $('.partial_box').html("<%= j (render 'car_serach') %>");
<% elsif @tag == "feature" %>
  $('.partial_box').html("<%= j (render 'feature_serach') %>");
<% end %>

app/views/home/index.html.slim
= stylesheet_link_tag "home/index", :media => "all"
= stylesheet_link_tag "flickity", :media => "all"
= javascript_include_tag "flickity.pkgd.min.js"

article
  ul.top_header.js-flickity
    section.top_header_inner
      =image_tag("top_image02.jpg")
      h1
        | 手間いらずで安心
        br
        | 格安マイカーシェアリング。
    li.gallery-cell
      =image_tag("top_image.png")
    li.gallery-cell
      =image_tag("top_image.png")
    li.gallery-cell
      =image_tag("top_image.png")
    li.gallery-cell
      =image_tag("top_image.png")
  .top_links
    p どちらでマイカーシェアリングを楽しみますか？
    .top_links_inner
      a.top_link href="/searchs"
        =image_tag("search_icon.png")
        .text_box
          | ドライバー
          br
          span として車を探す
      a.top_link href="/consider"
        =image_tag("car_icon.png", :class => "car_img")
        .text_box
          | オーナー
          br
          span として車を登録する
  section.content
    section.content_inner
      section.about
        h2
          | ワンズシェアってどんなサービス？
          br
          span ABOUT
        section.about_box.driver#driver
          h3
            | 車を借りる人
            br
            span DRIVER
          p.pc_about
            =image_tag("driver_flow_img.png")
          ul.sp_about.js-flickity01
            li.gallery-cell
              =image_tag("driver_step1.png")
            li.gallery-cell
              =image_tag("driver_step2.png")
            li.gallery-cell
              =image_tag("driver_step3.png")
            li.gallery-cell
              =image_tag("driver_step4.png")
          = link_to "もっと詳しく知りたい方はこちら", abouts_path, class: "about_box_link"
        section.about_box.owner#owner
          h3
            | 車を貸す人
            br
            span OWNER
          p.pc_about
            =image_tag("owner_flow_img.png")
          ul.sp_about.js-flickity01
            li.gallery-cell
              =image_tag("owner_step1.png")
            li.gallery-cell
              =image_tag("owner_step2.png")
            li.gallery-cell
              =image_tag("owner_step3.png")
            li.gallery-cell
              =image_tag("owner_step4.png")
          = link_to "オーナーを検討されている方はこちら", consider_path, class: "about_box_link"
      section.serch
        h2
          | 車を探す
          br
          span SEARCH
        .partial_box
          =render partial: "area_serach"

      section.experience
        h2
          | 安心・安全なワンズシェア
          br
          span EXPERIENCE
        p.experience_copy ワンズシェアは「個人間カーシェアリングの問題」を解決します。
        p.experience_pc_img
          =image_tag("experience.png")
        p.experience_sp_img
          =image_tag("experience_sp.png")
      section.review
        h2
          | 利用者の感想
          br
          span REVIEW
        =render partial: "review"


      section.news
        h2
          | ニュース
          br
          span NEWS
        =render partial: "news"
        = link_to "もっと見る", news_index_path, class: "news_more_link"

javascript:
  $(function() {
    $('.js-flickity').flickity({
      wrapAround: true
    });
    $('.js-flickity01').flickity({
      wrapAround: false
    });
  });

app/views/home/news.html.slim
= stylesheet_link_tag "home/news", :media => "all"
article
  section.news
    h2
      | ニュース
      br
      span NEWS
    =render partial: "news"