config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :sessions      => "users/sessions",
    :registrations => "users/registrations",
    :passwords     => "users/passwords",
  }
  root 'home#index'
  get '/home_serach' => 'home#home_serach'

  resources :abouts, only: [:index]
  resources :searchs, only: [:index]
  resources :car_searchs, only: [:index]
  get '/detail_search' => 'car_searchs#detail_search'
  resources :questions, only: [:index]
  resources :news, only: [:index]
  resources :stores, only: [:index]
  resources :cars, only: [:index]
  post '/reserve' => 'cars#reserve'
  get '/reserved' => 'cars#reserved'

  resources :mypages, only: [:index]
  get '/profile' => 'mypages#profile'
  post '/profile_create' => 'mypages#profile_create'
  patch '/profile_update' => 'mypages#profile_update'
  get '/license' => 'mypages#license'
  post '/license_create' => 'mypages#license_create'
  patch '/license_update' => 'mypages#license_update'
  get '/review' => 'mypages#review'
  post '/review_create' => 'mypages#review_create'
  get '/notification' => 'mypages#notification'
  post '/notification_set' => 'mypages#notification_set'
  get '/payment' => 'mypages#payment'
  get '/privacy' => 'mypages#privacy'
  get '/password' => 'mypages#password'
  post '/password_set' => 'mypages#password_set'
  get '/detail' => 'mypages#detail'
  post '/detail_set' => 'mypages#detail_set'
  get '/reservation' => 'mypages#reservation'

  resources :ownerpages, only: [:index]
  get '/entry' => 'ownerpages#entry'
  post '/owner_create' => 'ownerpages#owner_create'
  get '/performance' => 'ownerpages#performance'
  get '/revenue' => 'ownerpages#revenue'
  get '/consider' => 'ownerpages#consider'
  get '/not_approval' => 'ownerpages#not_approval'
  get '/not_acceptance' => 'ownerpages#not_acceptance'
  get '/car_edit' => 'ownerpages#car_edit'
  patch '/car_update' => 'ownerpages#car_update'
  get '/owner_profile' => 'ownerpages#owner_profile'
  patch '/owner_profile_update' => 'ownerpages#owner_profile_update'
  get '/owner_license' => 'ownerpages#owner_license'
  patch '/owner_license_update' => 'ownerpages#owner_license_update'
  get '/owner_notification' => 'ownerpages#owner_notification'
  get '/owner_account' => 'ownerpages#owner_account'
  post '/owner_account_create' => 'ownerpages#owner_account_create'
  patch '/owner_account_update' => 'ownerpages#owner_account_update'
  get '/owner_privacy' => 'ownerpages#owner_privacy'
  get '/owner_password' => 'ownerpages#owner_password'
  get '/owner_detail' => 'ownerpages#owner_detail'
  post '/store_select' => 'ownerpages#store_select'


  resources :reserve_conditions, only: [:index]
  get '/reserve01' => 'reserves#reserve01'
  get '/reserve02' => 'reserves#reserve02'
  get '/reserve03' => 'reserves#reserve03'
  post '/pay' => 'reserves#pay'

  resources :admins, only: [:index]
  get '/admin_store' => 'admins#admin_store'
  post '/admin_store_create' => 'admins#admin_store_create'
  get '/admin_license' => 'admins#admin_license'
  get '/admin_user' => 'admins#admin_user'
  patch '/role_change' => 'admins#role_change'
  patch '/store_change' => 'admins#store_change'
  get '/admin_store_edit' => 'admins#admin_store_edit'
  patch '/admin_store_update' => 'admins#admin_store_update'
  get '/admin_license_approval' => 'admins#admin_license_approval'
  get '/admin_reservation' => 'admins#admin_reservation'
  get '/admin_return_car' => 'admins#admin_return_car'

  resources :store_admins, only: [:index]
  get '/owner_entry' => 'store_admins#owner_entry'
  get '/owner_acceptance' => 'store_admins#owner_acceptance'
  get '/store_admin_edit' => 'store_admins#store_admin_edit'
  patch '/store_admin_update' => 'store_admins#store_admin_update'
  get '/owner_entry_infomation' => 'store_admins#owner_entry_infomation'
  post '/owner_approval' => 'store_admins#owner_approval'
  get '/owner_acceptance_car' => 'store_admins#owner_acceptance_car'
  get '/acceptance_car' => 'store_admins#acceptance_car'
  post '/owner_car_create' => 'store_admins#owner_car_create'
  get '/acceptance_car_edit' => 'store_admins#acceptance_car_edit'
  patch '/acceptance_car_update' => 'store_admins#acceptance_car_update'
  get '/store_admin_reservation' => 'store_admins#store_admin_reservation'
  get '/receipt_date_set' => 'store_admins#receipt_date_set'
  get '/store_return_car' => 'store_admins#store_return_car'
end

app/controllers/store_admins_controller.rb
class StoreAdminsController < ApplicationController

  def index
    @store = current_user.try(:store)
  end

  def owner_entry
    @store = current_user.try(:store)
    @owners = Owner.where(store_id: @store.id, approval: false)
  end

  def owner_acceptance
    @store = current_user.try(:store)
    @owners = Owner.where(store_id: @store.id, approval: true, acceptance: false)
  end

  def store_admin_edit
    @store = current_user.try(:store)
  end

  def owner_entry_infomation
    @store = current_user.try(:store)
    @owner = Owner.find(params[:id])
  end

  def store_admin_update
    store = Store.find(params[:id])
    store.update(store_params)
    redirect_to store_admins_path
  end

  def owner_approval
    owner = Owner.find(params[:id])
    store = current_user.try(:store)
    owner.update(approval: true, receipt_date: params[:receipt_date])
    OwnerEntryMailer.owner_notification(owner, store).deliver_now
  end

  def owner_acceptance_car
    @owner = Owner.find(params[:id])
    @store = current_user.try(:store)
  end

  def acceptance_car
    @store = current_user.try(:store)
    store = current_user.try(:store)
    @cars = Car.where(store_id: store.id)
  end

  def acceptance_car_edit
    @store = current_user.try(:store)
    @car = Car.find(params[:id])
  end

  def acceptance_car_update
    @car = Car.find(params[:id])
    @car.update(car_params)
    redirect_to acceptance_car_path
  end

  def owner_car_create
    car = Car.new(car_params)
    if car.save
      car.price_set
      owner = Owner.find(car.owner_id)
      owner.update(acceptance: true)
      redirect_to acceptance_car_path
    end
  end

  def store_admin_reservation
    @store = current_user.try(:store)
    @reservations = Reservation.joins(:car).where(:cars => {store_id: @store.id}).page(params[:page]).per(10)
  end

  def receipt_date_set
    @store = current_user.try(:store)
  end

  def store_return_car
    reservation = Reservation.find(params[:res_id])
    if params[:tab] == "rental"
      reservation.update(state: "rental")
    elsif params[:tab] == "returned"
      reservation.update(state: "returned")
      CarReturnMailer.returned_notification(reservation.user, reservation.car).deliver_now
    end
    redirect_to store_admin_reservation_path
  end

  private
  def store_params
    params.require(:store).permit!
  end

  def car_params
    params.require(:car).permit!
  end
end

app/views/store_admins/acceptance_car.html.slim
= stylesheet_link_tag "home/store_admin", :media => "all"

article
  section.store_admin
    h1 #{@store.name} 管理画面
    .contents
      .nav_toggle_button メニュー
      .ownerpage_nav
        ul
          li
            = link_to "店舗情報", store_admins_path
          li
            = link_to "車受け取り可能時間設定", receipt_date_set_path
          li
            = link_to "オーナー申請一覧", owner_entry_path
          li
            = link_to "車受け取り予定", owner_acceptance_path
          li
            = link_to "登録車一覧", acceptance_car_path, class: "selected"
          li
            = link_to "予約一覧", store_admin_reservation_path
      .store_admin_contents
        h2 登録車一覧
        .store_admin_contents_inner
          .store_admin_carlists
            table
              thead
                tr
                  th 車名
                  th 車種
                  th オーナー名
                  th
              tbody
                -@cars.each do |car|
                  tr
                    td = car.name
                    td M
                    td オーナー名
                    td =link_to "編集", acceptance_car_edit_path(id: car.id)

app/views/store_admins/acceptance_car_edit.html.slim
= stylesheet_link_tag "home/store_admin", :media => "all"

article
  section.store_admin
    h1 #{@store.name} 管理画面
    .contents
      .nav_toggle_button メニュー
      .ownerpage_nav
        ul
          li
            = link_to "店舗情報", store_admins_path
          li
            = link_to "車受け取り可能時間設定", receipt_date_set_path
          li
            = link_to "オーナー申請一覧", owner_entry_path
          li
            = link_to "車受け取り予定", owner_acceptance_path
          li
            = link_to "登録車一覧", acceptance_car_path, class: "selected"
          li
            = link_to "予約一覧", store_admin_reservation_path
      .store_admin_contents
        h2 登録車編集
        .store_admin_contents_inner
          =simple_nested_form_for @car, url: acceptance_car_update_path(id: @car.id)  do |f|
            p 名前
            = f.input :name, label: false, require: true
            p 説明
            = f.input :description, label: false, require: true
            p 席数
            = f.input :seat, label: false, require: true
            p カテゴリー
            = f.input :category_id, label: false, require: true, collection: Category.all, label_method: :name, value_method: :id
            = f.simple_fields_for :car_options do |f2|
              p オプション
              =f2.input :option_id, label: false, require: true, collection: Option.all, label_method: :name, value_method: :id
              =f2.link_to_remove "条件を削除"
            = f.link_to_add "オプションを追加", :car_options
            = f.simple_fields_for :car_images do |f3|
              p 車の画像
              =f3.input :image, label: false, require: true, as: :file
              =f3.link_to_remove "画像を削除"
            = f.link_to_add "画像を追加", :car_images
            = f.button :submit, "更新"

app/views/store_admins/index.html.slim
= stylesheet_link_tag "home/store_admin", :media => "all"

article
  section.store_admin
    h1 #{@store.name} 管理画面
    .contents
      .nav_toggle_button メニュー
      .ownerpage_nav
        ul
          li
            = link_to "店舗情報", store_admins_path, class: "selected"
          li
            = link_to "車受け取り可能時間設定", receipt_date_set_path
          li
            = link_to "オーナー申請一覧", owner_entry_path
          li
            = link_to "車受け取り予定", owner_acceptance_path
          li
            = link_to "登録車一覧", acceptance_car_path
          li
            = link_to "予約一覧", store_admin_reservation_path
      .store_admin_contents
        h2 店舗情報
        .store_admin_contents_inner
          .store_admin_info
            table
              tr
                th 店舗名
                td =@store.name
              tr
                th 電話番号
                td =@store.tel
              tr
                th メールアドレス
                td =@store.email
              tr
                th 店舗URL
                td =link_to "#{@store.url}", @store.url, target: "_blank"
              tr
                th アクセス
                td =@store.access
              tr
                th 郵便番号
                td =@store.zip_code
              tr
                th 住所
                td =@store.address
              tr
                th 営業開始時間
                td =@store.business_hour_start.strftime('%H:%M')
              tr
                th 営業終了時間
                td =@store.business_hour_end.strftime('%H:%M')
            =link_to '編集', store_admin_edit_path

app/views/store_admins/owner_acceptance.html.slim
= stylesheet_link_tag "home/store_admin", :media => "all"

article
  section.store_admin
    h1 #{@store.name} 管理画面
    .contents
      .nav_toggle_button メニュー
      .ownerpage_nav
        ul
          li
            = link_to "店舗情報", store_admins_path
          li
            = link_to "車受け取り可能時間設定", receipt_date_set_path
          li
            = link_to "オーナー申請一覧", owner_entry_path
          li
            = link_to "車受け取り予定", owner_acceptance_path, class: "selected"
          li
            = link_to "登録車一覧", acceptance_car_path
          li
            = link_to "予約一覧", store_admin_reservation_path
      .store_admin_contents
        h2 車受け取り予定一覧
        .store_admin_contents_inner
          .store_admin_ownerlists
            table
              thead
                tr
                  th オーナー名
                  th 受け取り車名
                  th 車種
                  th 車受け取り日時
                  th
              tbody
                -@owners.each do |owner|
                  tr
                    td =owner.name
                    td アルファード
                    td M
                    td 2019/2/2 19:00
                    td =link_to "受け取り確認をする", owner_acceptance_car_path(id: owner.id)

app/views/store_admins/owner_acceptance_car.html.slim
= stylesheet_link_tag "home/store_admin", :media => "all"

article
  section.store_admin
    h1 #{@store.name} 管理画面
    .contents
      .nav_toggle_button メニュー
      .ownerpage_nav
        ul
          li
            = link_to "店舗情報", store_admins_path
          li
            = link_to "車受け取り可能時間設定", receipt_date_set_path
          li
            = link_to "オーナー申請一覧", owner_entry_path
          li
            = link_to "車受け取り予定", owner_acceptance_path, class: "selected"
          li
            = link_to "登録車一覧", acceptance_car_path
          li
            = link_to "予約一覧", store_admin_reservation_path
      .store_admin_contents
        h2 受け取り車のチェック
        .store_admin_contents_inner
          = simple_nested_form_for Car.new, url: owner_car_create_path  do |f|
            p 名前
            = f.input :name, label: false, require: true
            p 説明
            = f.input :description, label: false, require: true
            p 席数
            = f.input :seat, label: false, require: true
            p カテゴリー
            = f.input :category_id, label: false, require: true, collection: Category.all, label_method: :name, value_method: :id
            = f.simple_fields_for :car_options do |f2|
              p オプション
              =f2.input :option_id, label: false, require: true, collection: Option.all, label_method: :name, value_method: :id
              =f2.link_to_remove "条件を削除"
            = f.link_to_add "オプションを追加", :car_options
            = f.simple_fields_for :car_images do |f3|
              p 車の画像
              =f3.input :image, label: false, require: true, as: :file
              =f3.link_to_remove "画像を削除"
            = f.link_to_add "画像を追加", :car_images

            = f.input :owner_id, as: :hidden, input_html: {value: @owner.id}
            = f.input :store_id, as: :hidden, input_html: {value: @store.id}
            = f.button :submit, "車を登録する"

app/views/store_admins/owner_entry.html.slim
= stylesheet_link_tag "home/store_admin", :media => "all"

article
  section.store_admin
    h1 #{@store.name} 管理画面
    .contents
      .nav_toggle_button メニュー
      .ownerpage_nav
        ul
          li
            = link_to "店舗情報", store_admins_path
          li
            = link_to "車受け取り可能時間設定", receipt_date_set_path
          li
            = link_to "オーナー申請一覧", owner_entry_path
          li
            = link_to "車受け取り予定", owner_acceptance_path
          li
            = link_to "登録車一覧", acceptance_car_path
          li
            = link_to "予約一覧", store_admin_reservation_path
      .store_admin_contents
        h2 オーナー申請一覧
        .store_admin_contents_inner
          .store_admin_ownerlists
            table
              thead
                tr
                  th 名前
                  th 車名
                  th 車種
                  th 申請日時
                  th
              tbody
                -@owners.each do |owner|
                  tr
                    td = owner.name
                    td アルファード
                    td M
                    td 2019/2/2 13:45
                    td =link_to "詳細", owner_entry_infomation_path(id: owner.id)

app/views/store_admins/owner_entry_infomation.html.slim
= stylesheet_link_tag "home/store_admin", :media => "all"

article
  section.store_admin
    h1 #{@store.name} 管理画面
    .contents
      .nav_toggle_button メニュー
      .ownerpage_nav
        ul
          li
            = link_to "店舗情報", store_admins_path
          li
            = link_to "車受け取り可能時間設定", receipt_date_set_path
          li
            = link_to "オーナー申請一覧", owner_entry_path
          li
            = link_to "車受け取り予定", owner_acceptance_path
          li
            = link_to "登録車一覧", acceptance_car_path
          li
            = link_to "予約一覧", store_admin_reservation_path
      .store_admin_contents
        h2 オーナーの承認と車受け取り日時の確定
        .store_admin_contents_inner
          .store_admin_owner_entry
            table
              tr
                th 名前
                td =@owner.name
              tr
                th 住所
                td =@owner.address
              tr
                th 生年月日
                td =@owner.birth_day
              tr
                th 希望日時（ 選択してください ）
                td = select_tag 'receipt_date', options_for_select([["#{@owner.first_receipt_date.strftime('%Y年%m月%d日%H:%M')}"], ["#{@owner.second_receipt_date.strftime('%Y年%m月%d日%H:%M')}"], ["#{@owner.third_receipt_date.strftime('%Y年%m月%d日%H:%M')}"]])
            .store_admin_owner_entry_button
              = button_tag "日付を確認して承認する", type: 'submit', onclick: "owner_approval()"


javascript:
  function owner_approval(){
    var id = "#{params[:id]}"
    var receipt_date = $('#receipt_date')[0].value
    $.ajax({
      type: 'post',
      url: '/owner_approval',
      dataType: 'html',
      data: {receipt_date: receipt_date, id: id},
      success: function(data){
        window.location.href = '/owner_entry';
      }
    });
  }

app/views/store_admins/receipt_date_set.html.slim
= stylesheet_link_tag "home/store_admin", :media => "all"

article
  section.store_admin
    h1 #{@store.name} 管理画面
    .contents
      .nav_toggle_button メニュー
      .ownerpage_nav
        ul
          li
            = link_to "店舗情報", store_admins_path, class: "selected"
          li
            = link_to "車受け取り可能時間設定", receipt_date_set_path
          li
            = link_to "オーナー申請一覧", owner_entry_path
          li
            = link_to "車受け取り予定", owner_acceptance_path
          li
            = link_to "登録車一覧", acceptance_car_path
          li
            = link_to "予約一覧", store_admin_reservation_path
      .store_admin_contents
        h2 車受け取り可能時間設定
        .store_admin_contents_inner
          =simple_form_for @store, url: store_admin_update_path(id: @store.id)  do |f|
            p 受け取り可能時間
            = f.input :receipt_description, label: false
            = f.button :submit, "更新"

app/views/store_admins/store_admin_edit.html.slim
= stylesheet_link_tag "home/store_admin", :media => "all"

article
  section.store_admin
    h1 #{@store.name} 管理画面
    .contents
      .nav_toggle_button メニュー
      .ownerpage_nav
        ul
          li
            = link_to "店舗情報", store_admins_path, class: "selected"
          li
            = link_to "車受け取り可能時間設定", receipt_date_set_path
          li
            = link_to "オーナー申請一覧", owner_entry_path
          li
            = link_to "車受け取り予定", owner_acceptance_path
          li
            = link_to "登録車一覧", acceptance_car_path
          li
            = link_to "予約一覧", store_admin_reservation_path
      .store_admin_contents
          h2 店舗情報編集
          .store_admin_contents_inner
            =simple_form_for @store, url: store_admin_update_path(id: @store.id)  do |f|
              p　店舗名
              = f.input :name, label: false
              p 電話番号
              = f.input :tel, label: false
              p メールアドレス
              = f.input :email, label: false
              p 画像
              = f.input :image, label: false, as: :file
              p 店舗URL
              = f.input :url, label: false
              p アクセス
              = f.input :access, label: false
              p 営業開始時間
              = f.input :business_hour_start, label: false
              p 営業終了時間
              = f.input :business_hour_end, label: false
              p 郵便番号
              = f.input :zip_code, label: false
              p 住所
              = f.input :address, label: false
              p 緯度(Map表示用)
              =link_to "こちらに住所を入力で検索可能", "https://www.geocoding.jp", target: "_blank"
              = f.input :latitude, label: false
              p 経度(Map表示用)
              =link_to "こちらに住所を入力で検索可能", "https://www.geocoding.jp", target: "_blank"
              = f.input :longitude, label: false
              p 都道府県(検索用)
              = f.input :prefecture_id, label: false, collection: Prefecture.all, label_method: :name, value_method: :id
              = f.button :submit, "更新"

app/views/store_admins/store_admin_reservation.html.slim
= stylesheet_link_tag "home/store_admin", :media => "all"

article
  section.store_admin
    h1 #{@store.name} 管理画面
    .contents
      .nav_toggle_button メニュー
      .ownerpage_nav
        ul
          li
            = link_to "店舗情報", store_admins_path
          li
            = link_to "車受け取り可能時間設定", receipt_date_set_path
          li
            = link_to "オーナー申請一覧", owner_entry_path
          li
            = link_to "車受け取り予定", owner_acceptance_path
          li
            = link_to "登録車一覧", acceptance_car_path
          li
            = link_to "予約一覧", store_admin_reservation_path, class: "selected"
      .store_admin_contents
        .store_admin_contents_inner
          .store_admin_reservelists
            table
              thead
                tr
                  th 車名
                  th 予約日
                  th 返却日
                  th 料金
                  th 状態
              tbody
                -@reservations.each do |reservation|
                  tr
                    td = reservation.car.name
                    td #{reservation.start_date.strftime('%Y年%m月%d日')}#{reservation.start_time.strftime('%H:%M')}
                    td #{reservation.end_date.strftime('%Y年%m月%d日')}#{reservation.end_time.strftime('%H:%M')}
                    td = reservation.total
                    td
                      -if reservation.state == "returned"
                        p 返却ずみ
                      -elsif reservation.state == "rental"
                        =link_to "返却完了", admin_return_car_path(res_id: reservation.id, tab: "returned")
                      -elsif reservation.state == "acceptance"
                        =link_to "受け渡し完了", admin_return_car_path(res_id: reservation.id, tab: "rental")
                = paginate @reservations