config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :sessions      => "users/sessions",
    :registrations => "users/registrations",
    :passwords     => "users/passwords",
  }
  root 'home#index'
  get '/home_serach' => 'home#home_serach'

  resources :abouts, only: [:index]
  resources :searchs, only: [:index]
  resources :car_searchs, only: [:index]
  get '/detail_search' => 'car_searchs#detail_search'
  resources :questions, only: [:index]
  resources :news, only: [:index]
  resources :stores, only: [:index]
  resources :cars, only: [:index]
  post '/reserve' => 'cars#reserve'
  get '/reserved' => 'cars#reserved'

  resources :mypages, only: [:index]
  get '/profile' => 'mypages#profile'
  post '/profile_create' => 'mypages#profile_create'
  patch '/profile_update' => 'mypages#profile_update'
  get '/license' => 'mypages#license'
  post '/license_create' => 'mypages#license_create'
  patch '/license_update' => 'mypages#license_update'
  get '/review' => 'mypages#review'
  post '/review_create' => 'mypages#review_create'
  get '/notification' => 'mypages#notification'
  post '/notification_set' => 'mypages#notification_set'
  get '/payment' => 'mypages#payment'
  get '/privacy' => 'mypages#privacy'
  get '/password' => 'mypages#password'
  post '/password_set' => 'mypages#password_set'
  get '/detail' => 'mypages#detail'
  post '/detail_set' => 'mypages#detail_set'
  get '/reservation' => 'mypages#reservation'

  resources :ownerpages, only: [:index]
  get '/entry' => 'ownerpages#entry'
  post '/owner_create' => 'ownerpages#owner_create'
  get '/performance' => 'ownerpages#performance'
  get '/revenue' => 'ownerpages#revenue'
  get '/consider' => 'ownerpages#consider'
  get '/not_approval' => 'ownerpages#not_approval'
  get '/not_acceptance' => 'ownerpages#not_acceptance'
  get '/car_edit' => 'ownerpages#car_edit'
  patch '/car_update' => 'ownerpages#car_update'
  get '/owner_profile' => 'ownerpages#owner_profile'
  patch '/owner_profile_update' => 'ownerpages#owner_profile_update'
  get '/owner_license' => 'ownerpages#owner_license'
  patch '/owner_license_update' => 'ownerpages#owner_license_update'
  get '/owner_notification' => 'ownerpages#owner_notification'
  get '/owner_account' => 'ownerpages#owner_account'
  post '/owner_account_create' => 'ownerpages#owner_account_create'
  patch '/owner_account_update' => 'ownerpages#owner_account_update'
  get '/owner_privacy' => 'ownerpages#owner_privacy'
  get '/owner_password' => 'ownerpages#owner_password'
  get '/owner_detail' => 'ownerpages#owner_detail'
  post '/store_select' => 'ownerpages#store_select'


  resources :reserve_conditions, only: [:index]
  get '/reserve01' => 'reserves#reserve01'
  get '/reserve02' => 'reserves#reserve02'
  get '/reserve03' => 'reserves#reserve03'
  post '/pay' => 'reserves#pay'

  resources :admins, only: [:index]
  get '/admin_store' => 'admins#admin_store'
  post '/admin_store_create' => 'admins#admin_store_create'
  get '/admin_license' => 'admins#admin_license'
  get '/admin_user' => 'admins#admin_user'
  patch '/role_change' => 'admins#role_change'
  patch '/store_change' => 'admins#store_change'
  get '/admin_store_edit' => 'admins#admin_store_edit'
  patch '/admin_store_update' => 'admins#admin_store_update'
  get '/admin_license_approval' => 'admins#admin_license_approval'
  get '/admin_reservation' => 'admins#admin_reservation'
  get '/admin_return_car' => 'admins#admin_return_car'

  resources :store_admins, only: [:index]
  get '/owner_entry' => 'store_admins#owner_entry'
  get '/owner_acceptance' => 'store_admins#owner_acceptance'
  get '/store_admin_edit' => 'store_admins#store_admin_edit'
  patch '/store_admin_update' => 'store_admins#store_admin_update'
  get '/owner_entry_infomation' => 'store_admins#owner_entry_infomation'
  post '/owner_approval' => 'store_admins#owner_approval'
  get '/owner_acceptance_car' => 'store_admins#owner_acceptance_car'
  get '/acceptance_car' => 'store_admins#acceptance_car'
  post '/owner_car_create' => 'store_admins#owner_car_create'
  get '/acceptance_car_edit' => 'store_admins#acceptance_car_edit'
  patch '/acceptance_car_update' => 'store_admins#acceptance_car_update'
  get '/store_admin_reservation' => 'store_admins#store_admin_reservation'
  get '/receipt_date_set' => 'store_admins#receipt_date_set'
  get '/store_return_car' => 'store_admins#store_return_car'
end

app/controllers/ownerpages_controller.rb
class OwnerpagesController < ApplicationController

  def index
    @owner = current_user.try(:owner)
    if @owner
      unless @owner.approval
        redirect_to not_approval_path
        return
      end
      unless @owner.acceptance
        redirect_to not_acceptance_path
        return
      end
      @cars = Car.where(owner_id: @owner.id)
    else
      redirect_to entry_path
      return
    end
  end

  def performance
    @owner = current_user.try(:owner)
    @reservations = Reservation.joins(:car).where(:cars => {owner_id: @owner.id})
  end

  def revenue
    @owner = current_user.try(:owner)
    @reservations = Reservation.where(start_date: Time.now.all_month).joins(:car).where(:cars => {owner_id: @owner.id})
    @total = 0
    @reservations.each do |re|
      @total += re.total
    end
  end

  def consider
  end

  def entry
  end

  def not_approval
  end

  def not_acceptance
    @owner = current_user.try(:owner)
    @store = @owner.store
    @hash = [{:lat=>@store.latitude, :lng=>@store.longitude}]
  end

  def car_edit
    @owner = current_user.try(:owner)
    @car = Car.find_by(id: params[:car_id], owner_id: @owner.id)
  end

  def car_update
  end

  def owner_profile
    @owner = current_user.try(:owner)
  end

  def owner_profile_update
  end

  def owner_license
    @license = License.new
  end

  def owner_license_update
  end

  def owner_notification
  end

  def owner_account
    @owner = current_user.try(:owner)
  end

  def owner_account_create
    account = Account.new(account_params)
    account.save
    redirect_to owner_account_path
  end

  def owner_account_update
    account = Account.find(params[:id])
    account.update(account_params)
    redirect_to owner_account_path
  end

  def owner_privacy
  end

  def owner_password
  end

  def owner_detail
  end

  def owner_create
    owner = Owner.new(owner_params)
    store = Store.find(owner_params[:store_id])
    car_name = owner_params[:car_name]
    if owner.save
      current_user.update(owner_id: owner.id)
    end
    OwnerEntryMailer.entry_notification(owner, store, car_name).deliver_now
    redirect_to ownerpages_path
  end

  def store_select
    @store = Store.find(params[:store_id])
  end

  private

  def owner_params
    params.require(:owner).permit!
  end

  def license_params
    params.require(:license).permit!
  end

  def account_params
    params.require(:account).permit!
  end


end

app/views/ownerpages/_owner_car_list.html.slim
ul.car_list_inner
  -@cars.each do |car|
    li.car_list_box
      = link_to cars_path(car_id: car.id) , class: "car_list_link" do
        .h2_box
          p #{car.price}円 / 1時間
          h2
            | #{car.name}
            span #{car.store.access}
        p.car_list_img
          =image_tag(car.car_images.first.image.to_s)
      .shop_info
        p
          | 受け取り場所
          = link_to "#{car.store.name}", car.store.url, target: "_blank"
      ul.option_list
        -car.options.each do |option|
          li =option.name
      .edit_car
        = link_to "編集", car_edit_path(car_id: car.id), class: "edit_car_link"

app/views/ownerpages/_store_receipt_date.html.slim
-if @store.present?
  -if @store.receipt_description.present?
    p 受け取り対応可能時間
    p =@store.receipt_description

app/views/ownerpages/car_edit.html.slim
= stylesheet_link_tag "home/ownerpage", :media => "all"

article
  section.ownerpage
    h1 オーナーページ
    .contents
      .nav_toggle_button オーナーメニューを開く
      .ownerpage_nav
        h2.first_h2
          =image_tag("car_list_img.jpg")
          span オーナー名
        ul
          li
            = link_to "プロフィールの編集", owner_profile_path
          li
            = link_to "免許証の確認", owner_license_path
        h2 アカウント
        ul
          /li
            = link_to "通知", owner_notification_path
          li
            = link_to "口座設定", owner_account_path
          /li
            = link_to "プライバシー", owner_privacy_path
          /li
            = link_to "パスワード設定", owner_password_path
          /li
            = link_to "各種設定", owner_detail_path
        h2 登録車
        ul
          li
            = link_to "登録車一覧", ownerpages_path, class: "selected"
        h2 実績
        ul
          li
            = link_to "実績", performance_path
          li
            = link_to "収入", revenue_path
      .ownerpage_contents
        =simple_form_for @car, url: car_update_path(id: @car.id)  do |f|
          p 名前
          = f.input :name, label: false
          p 説明
          = f.input :description, label: false
          p カテゴリー
          = f.input :category_id, label: false, collection: Category.all, label_method: :name, value_method: :id
          p 画像
          /= f.input :, label: false
          = f.button :submit, "更新"
  #close_area

javascript:
  $(function() {
    $('.nav_toggle_button').click(function () {
        $('.ownerpage_nav').slideToggle();
        $('#close_area').show();
    });
    $('#close_area').click(function () {
        $('.ownerpage_nav').slideToggle();
        $('#close_area').hide();
    });
  });

app/views/ownerpages/consider.html.slim
= stylesheet_link_tag "home/owner_consider", :media => "all"

article
  .breadcrumbs
      ul
        li
          = link_to "HOME", root_path
        li オーナーを検討されている方
  .owner_top
    .revenue_box
      p.title ワンズシェアのオーナー予想収入
      .revenue_box_inner
        /.text あなたのことを教えてください。
        /p.area 場所を選べるようにしたい
        /.select_box
          p 車種
          p 週5
        p.revenue_result
          | 51,720円
          span
            | （ 1ヶ月あたり )
        =link_to "オーナーになる", entry_path
  .revenue_bottom
    .bottom_box
      p 1ヶ月あたりの予想収入
      span 51,720円
      =link_to "オーナーになる", entry_path
  section.owner_consider
    h1
      | オーナーを検討されている方
      br
      span OWNER
    ul.consider_button
      li
        a.top_link href="/entry"
          =image_tag("car_icon.png")
          .text_box
            | 今すぐ
            br
            span オーナー登録
      li
        a.top_link href="/consider"
          =image_tag("study_icon.png", :class => "car_img")
          .text_box
            | まずは
            br
            span 詳しい内容を知る
    section.owner_about
      h2 ワンズシェアオーナーの最大の特徴
      h3 オーナー業務をワンズシェアが全て代行
      p.about_text ワンズシェアは、レンタル時に発生する面倒なオーナー業務を代行することで、オーナーにかかる負担を最大限に減らすことに尽力しています。普段の仕事や生活で忙しく、オーナーをやりたくてもできない方でも、ワンズシェアなら今すぐにマイカーシェアリングのオーナーをすることができ、車を貸し出すだけで収益を得られる仕組みを作りました。
    section.owner_merit
      h2 オーナーになるメリット
      ul.merit_lists
        li.left
          h3 個人間カーシェアリングの問題を解決
          .merit_content
            p.merit_img
              =image_tag("sharing.jpg")
            p ワンズシェアでは、車両の登録や、貸渡しから、傷のチェック、お客様とのトラブル交渉に到るまでワンズレンタカーが全て代行します。そのような方法をとることで、従来の個人間カーシェアシェアリングの問題を解決することが可能です。
        li.right
          h3 車の維持費を軽減することが可能
          .merit_content
            p.merit_img
              =image_tag("car_cost.jpg")
            p 自分が使わないときに車を貸すことで、売上が見込まれ、保険代などの車の維持費を軽減することができます。（受取金額は月20,000~30,000を見込みます）
        li.left
          h3 駐車場代の節約
          .merit_content
            p.merit_img
              =image_tag("parking.jpg")
            p ワンズシェアでは、車両を店舗が預かるという形を取っております。長期間登録店舗に預けることで駐車場代を節約することができます。
    section.owner_step
      h2 オーナーになるための3つのステップ
      p.title 手間いらず、「車を店舗に持っていくだけ」でオーナーに。
      ul
        li
          h3
            | 01
            span まずはオーナー登録
          p.step_img
            =image_tag("owner_consider_step1.png")
          p オーナーになるためのはじめのステップは、このページからオーナー登録をすることです。下のボタンからオーナー登録を済ませましょう。
        li
          h3
            | 02
            span 車を預ける店舗を決める
          p.step_img
            =image_tag("owner_consider_step2.png")
          p オーナー登録が完了したら、車を預ける店舗を探します。自分の車の種類を入力するだけで近くの店舗を探すことができます。店舗が決まれば、いつ、車を店舗に持っていくのかを決めます。
        li
          h3
            | 03
            span 店舗に車を持っていく
          p.step_img
            =image_tag("owner_consider_step3.png")
          p 指定された日に、車を店舗に持っていきましょう。車の情報登録やドライバーとのやりとりは全てワンズレンタカーのスタッフが対応。オーナーは面倒なやりとりなく、マイカーシェアリングをすることができます。
    section.owner_review
      h2 オーナー様たちの声
      ul
        li
          .profile_box
            p
              = image_tag("owner_img.png")
            span オーナー さん
            span 20代 男性
            span 千葉県 在住
          .comment_box テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト
        li.right
          .profile_box
            p
              = image_tag("owner_img.png")
            span オーナー さん
            span 20代 男性
            span 千葉県 在住
          .comment_box テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト
        li
          .profile_box
            p
              = image_tag("owner_img.png")
            span オーナー さん
            span 20代 男性
            span 千葉県 在住
          .comment_box テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト
        li.right
          .profile_box
            p
              = image_tag("owner_img.png")
            span オーナー さん
            span 20代 男性
            span 千葉県 在住
          .comment_box テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト
    section.owner_experience
      h2 安心・安全なワンズシェア
      p.experience_pc_img
          =image_tag("experience.png")
      p.experience_sp_img
        =image_tag("experience_sp.png")
    section.owner_quesition
      h2 Q&A
      h3 ログイン方法について
      ul
        li
          .question_toggle 会員登録は無料ですか？
          .answer 会員登録やクルマの登録は、無料です。プラットフォーム手数料として、オーナーは使用料の10％を負担いただきます。詳細は、特定商取引法の表示等をご覧ください。
        li
          .question_toggle 会員登録は無料ですか？
          .answer 会員登録やクルマの登録は、無料です。プラットフォーム手数料として、オーナーは使用料の10％を負担いただきます。詳細は、特定商取引法の表示等をご覧ください。
      h3 ログイン方法について
      ul
        li
          .question_toggle 会員登録は無料ですか？
          .answer 会員登録やクルマの登録は、無料です。プラットフォーム手数料として、オーナーは使用料の10％を負担いただきます。詳細は、特定商取引法の表示等をご覧ください。
        li
          .question_toggle 会員登録は無料ですか？
          .answer 会員登録やクルマの登録は、無料です。プラットフォーム手数料として、オーナーは使用料の10％を負担いただきます。詳細は、特定商取引法の表示等をご覧ください。
    section.owner_resigtraiton
      h2 オーナー登録はこちら
      = link_to "オーナー登録をする", entry_path


javascript:
  $(function(){
    $('.question_toggle').click(function(){
      $(this).toggleClass("open");
      $(this).next(".answer").slideToggle();
    });
  });

app/views/ownerpages/index.html.slim
= stylesheet_link_tag "home/ownerpage", :media => "all"

article
  section.ownerpage
    h1 オーナーページ
    .contents
      .nav_toggle_button オーナーメニューを開く
      .ownerpage_nav
        h2.first_h2
          =image_tag("car_list_img.jpg")
          span オーナー名
        ul
          li
            = link_to "プロフィールの編集", owner_profile_path
          li
            = link_to "免許証の確認", owner_license_path
        h2 アカウント
        ul
          /li
            = link_to "通知", owner_notification_path
          li
            = link_to "口座設定", owner_account_path
          /li
            = link_to "プライバシー", owner_privacy_path
          /li
            = link_to "パスワード設定", owner_password_path
          /li
            = link_to "各種設定", owner_detail_path
        h2 登録車
        ul
          li
            = link_to "登録車一覧", ownerpages_path, class: "selected"
        h2 実績
        ul
          li
            = link_to "実績", performance_path
          li
            = link_to "収入", revenue_path
      .ownerpage_contents
        =render partial: "owner_car_list"
  #close_area

javascript:
  $(function() {
    $('.nav_toggle_button').click(function () {
        $('.ownerpage_nav').slideToggle();
        $('#close_area').show();
    });
    $('#close_area').click(function () {
        $('.ownerpage_nav').slideToggle();
        $('#close_area').hide();
    });
  });

app/views/ownerpages/not_approval.html.slim
= stylesheet_link_tag "home/ownerpage", :media => "all"

article
  section.ownerpage
    h1 オーナーページ
    .contents
      .ownerpage_nav
        h2.first_h2
          =image_tag("car_list_img.jpg")
          span オーナー名
        ul
          li
            = link_to "承認待ち", ownerpages_path
      .close_button 閉じる
      .ownerpage_contents
        p.owner_wait_condition 店舗の承認待ち
        p.owner_wait 現在、店舗へオーナー登録の申請をしております。店舗の承認が得られるまでしばらくお待ち下さい。承認には1日~3日かかる場合がございます。承認がされた場合、登録されたメールアドレスにお知らせ致します。

app/views/ownerpages/owner_detail.html.slim
= stylesheet_link_tag "home/ownerpage", :media => "all"


article
  section.ownerpage
    h1 オーナーページ
    .contents
      .nav_toggle_button オーナーメニューを開く
      .ownerpage_nav
        h2.first_h2
          =image_tag("car_list_img.jpg")
          span オーナー名
        ul
          li
            = link_to "プロフィールの編集", owner_profile_path
          li
            = link_to "免許証の確認", owner_license_path
        h2 アカウント
        ul
          /li
            = link_to "通知", owner_notification_path
          li
            = link_to "口座設定", owner_account_path
          /li
            = link_to "プライバシー", owner_privacy_path
          /li
            = link_to "パスワード設定", owner_password_path
          /li
            = link_to "各種設定", owner_detail_path, class: "selected"
        h2 登録車
        ul
          li
            = link_to "登録車一覧", ownerpages_path
        h2 実績
        ul
          li
            = link_to "実績", performance_path
          li
            = link_to "収入", revenue_path

  #close_area

javascript:
  $(function() {
    $('.nav_toggle_button').click(function () {
        $('.ownerpage_nav').slideToggle();
        $('#close_area').show();
    });
    $('#close_area').click(function () {
        $('.ownerpage_nav').slideToggle();
        $('#close_area').hide();
    });
  });

app/views/ownerpages/owner_license.html.slim
= stylesheet_link_tag "home/ownerpage", :media => "all"

article
  section.ownerpage
    h1 オーナーページ
    .contents
      .nav_toggle_button オーナーメニューを開く
      .ownerpage_nav
        h2.first_h2
          =image_tag("car_list_img.jpg")
          span オーナー名
        ul
          li
            = link_to "プロフィールの編集", owner_profile_path
          li
            = link_to "免許証の確認", owner_license_path, class: "selected"
        h2 アカウント
        ul
          /li
            = link_to "通知", owner_notification_path
          li
            = link_to "口座設定", owner_account_path
          /li
            = link_to "プライバシー", owner_privacy_path
          /li
            = link_to "パスワード設定", owner_password_path
          /li
            = link_to "各種設定", owner_detail_path
        h2 登録車
        ul
          li
            = link_to "登録車一覧", ownerpages_path
        h2 実績
        ul
          li
            = link_to "実績", performance_path
          li
            = link_to "収入", revenue_path
      .ownerpage_contents
        .profile_edit
          -if @license.approval
            p 承認済み
          -else
            p 未承認
          =simple_form_for @license, url: owner_license_update_path(id: @license)  do |f|
            p　画像
            = f.input :image, label: false, as: :file
            = f.button :submit, "更新"
  #close_area

javascript:
  $(function() {
    $('.nav_toggle_button').click(function () {
        $('.ownerpage_nav').slideToggle();
        $('#close_area').show();
    });
    $('#close_area').click(function () {
        $('.ownerpage_nav').slideToggle();
        $('#close_area').hide();
    });
  });

app/views/ownerpages/owner_password.html.slim
= stylesheet_link_tag "home/ownerpage", :media => "all"

article
  section.ownerpage
    h1 オーナーページ
    .contents
      .nav_toggle_button オーナーメニューを開く
      .ownerpage_nav
        h2.first_h2
          =image_tag("car_list_img.jpg")
          span オーナー名
        ul
          li
            = link_to "プロフィールの編集", owner_profile_path
          li
            = link_to "免許証の確認", owner_license_path
        h2 アカウント
        ul
          /li
            = link_to "通知", owner_notification_path
          li
            = link_to "口座設定", owner_account_path
          /li
            = link_to "プライバシー", owner_privacy_path
          /li
            = link_to "パスワード設定", owner_password_path, class: "selected"
          /li
            = link_to "各種設定", owner_detail_path
        h2 登録車
        ul
          li
            = link_to "登録車一覧", ownerpages_path
        h2 実績
        ul
          li
            = link_to "実績", performance_path
          li
            = link_to "収入", revenue_path

  #close_area

javascript:
  $(function() {
    $('.nav_toggle_button').click(function () {
        $('.ownerpage_nav').slideToggle();
        $('#close_area').show();
    });
    $('#close_area').click(function () {
        $('.ownerpage_nav').slideToggle();
        $('#close_area').hide();
    });
  });

app/views/ownerpages/owner_privacy.html.slim
= stylesheet_link_tag "home/ownerpage", :media => "all"

article
  section.ownerpage
    h1 オーナーページ
    .contents
      .nav_toggle_button オーナーメニューを開く
      .ownerpage_nav
        h2.first_h2
          =image_tag("car_list_img.jpg")
          span オーナー名
        ul
          li
            = link_to "プロフィールの編集", owner_profile_path
          li
            = link_to "免許証の確認", owner_license_path
        h2 アカウント
        ul
          /li
            = link_to "通知", owner_notification_path
          li
            = link_to "口座設定", owner_account_path
          /li
            = link_to "プライバシー", owner_privacy_path, class: "selected"
          /li
            = link_to "パスワード設定", owner_password_path
          /li
            = link_to "各種設定", owner_detail_path
        h2 登録車
        ul
          li
            = link_to "登録車一覧", ownerpages_path
        h2 実績
        ul
          li
            = link_to "実績", performance_path
          li
            = link_to "収入", revenue_path


  #close_area

javascript:
  $(function() {
    $('.nav_toggle_button').click(function () {
        $('.ownerpage_nav').slideToggle();
        $('#close_area').show();
    });
    $('#close_area').click(function () {
        $('.ownerpage_nav').slideToggle();
        $('#close_area').hide();
    });
  });

app/views/ownerpages/performance.html.slim
= stylesheet_link_tag "home/ownerpage", :media => "all"

article
  section.ownerpage
    h1 オーナーページ
    .contents
      .nav_toggle_button オーナーメニューを開く
      .ownerpage_nav
        h2.first_h2
          =image_tag("car_list_img.jpg")
          span オーナー名
        ul
          li
            = link_to "プロフィールの編集", owner_profile_path
          li
            = link_to "免許証の確認", owner_license_path
        h2 アカウント
        ul
          /li
            = link_to "通知", owner_notification_path
          li
            = link_to "口座設定", owner_account_path
          /li
            = link_to "プライバシー", owner_privacy_path
          /li
            = link_to "パスワード設定", owner_password_path
          /li
            = link_to "各種設定", owner_detail_path
        h2 登録車
        ul
          li
            = link_to "登録車一覧", ownerpages_path
        h2 実績
        ul
          li
            = link_to "実績", performance_path, class: "selected"
          li
            = link_to "収入", revenue_path
      .ownerpage_contents
        .performance
          ul
            -@reservations.each do |reservation|
              li
                .performance_title
                  = link_to "#{reservation.car.name}", cars_path(car_id: reservation.car.id)
                  p #{reservation.start_date.strftime('%Y年%m月%d日')}#{reservation.start_time.strftime('%H:%M')}　→　#{reservation.end_date.strftime('%Y年%m月%d日')}#{reservation.end_time.strftime('%H:%M')}
                p.performance_money +#{reservation.total}円
                .performance_info
                  -if reservation.user.try(:profile)
                    p.guest_img
                      =image_tag(reservation.user.profile.image.to_s)
                    .guest_name
                      p =reservation.user.profile.name
  #close_area

javascript:
  $(function() {
    $('.nav_toggle_button').click(function () {
        $('.ownerpage_nav').slideToggle();
        $('#close_area').show();
    });
    $('#close_area').click(function () {
        $('.ownerpage_nav').slideToggle();
        $('#close_area').hide();
    });
  });

app/views/ownerpages/revenue.html.slim
= stylesheet_link_tag "home/ownerpage", :media => "all"

article
  section.ownerpage
    h1 オーナーページ
    .contents
      .nav_toggle_button オーナーメニューを開く
      .ownerpage_nav
        h2.first_h2
          =image_tag("car_list_img.jpg")
          span オーナー名
        ul
          li
            = link_to "プロフィールの編集", owner_profile_path
          li
            = link_to "免許証の確認", owner_license_path
        h2 アカウント
        ul
          /li
            = link_to "通知", owner_notification_path
          li
            = link_to "口座設定", owner_account_path
          /li
            = link_to "プライバシー", owner_privacy_path
          /li
            = link_to "パスワード設定", owner_password_path
          /li
            = link_to "各種設定", owner_detail_path
        h2 登録車
        ul
          li
            = link_to "登録車一覧", ownerpages_path
        h2 実績
        ul
          li
            = link_to "実績", performance_path
          li
            = link_to "収入", revenue_path, class: "selected"
      .ownerpage_contents
        .revenue
          ul.revenue_select
            li.selected 今月
            /li
              = link_to "2018年", revenue_path
            /li
              = link_to "全期間", revenue_path
          .total_revenue
            p #{@total}円
            span 月末に登録口座に振り込まれます。
          ul.revenue_list
            -@reservations.each do |reservation|
              li
                p.revenue_list_money +#{reservation.total}円
                p.revenue_list_info
                  = link_to "#{reservation.car.name}", cars_path(car_id: reservation.car_id), class: "car_link"
                  span #{reservation.start_date.strftime('%Y年%m月%d日')}#{reservation.start_time.strftime('%H:%M')}　→　#{reservation.end_date.strftime('%Y年%m月%d日')}#{reservation.end_time.strftime('%H:%M')}
                  /= link_to "詳細", cars_path, class: "resereve_link"

  #close_area

javascript:
  $(function() {
    $('.nav_toggle_button').click(function () {
        $('.ownerpage_nav').slideToggle();
        $('#close_area').show();
    });
    $('#close_area').click(function () {
        $('.ownerpage_nav').slideToggle();
        $('#close_area').hide();
    });
  });

app/views/ownerpages/store_select.js.erb
$('#store_receipt_date').html("<%= j (render 'store_receipt_date') %>");